import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

function bar(value: number, max: number = 10, width: number = 20): string {
  const filled = Math.round((value / max) * width);
  return "█".repeat(filled) + "░".repeat(width - filled);
}

function generateMarkdownReport(r: any): string {
  const scoreColor = (s: number) => s >= 7 ? "🟢" : s >= 5 ? "🟡" : "🔴";
  const checkMark = (b: boolean) => b ? "✅" : "❌";

  return `# RepoInsight Health Report
## ${r.owner}/${r.repo_name}

**Generated:** ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
**Repository:** ${r.repo_url}
**Language:** ${r.language || "Unknown"}
**Description:** ${r.description || "No description"}

---

## Overall Quality Score: ${Number(r.score).toFixed(1)}/10 ${scoreColor(Number(r.score))}

${bar(Number(r.score))} ${Number(r.score).toFixed(1)}/10

---

## Score Breakdown

| Category | Score | Rating |
|----------|-------|--------|
| Documentation | ${Number(r.documentation_score).toFixed(1)}/10 | ${scoreColor(Number(r.documentation_score))} |
| Maintainability | ${Number(r.maintainability_score).toFixed(1)}/10 | ${scoreColor(Number(r.maintainability_score))} |
| Structure | ${Number(r.structure_score).toFixed(1)}/10 | ${scoreColor(Number(r.structure_score))} |
| Community Health | ${Number(r.community_health_score).toFixed(1)}/10 | ${scoreColor(Number(r.community_health_score))} |
| Activity | ${Number(r.activity_score).toFixed(1)}/10 | ${scoreColor(Number(r.activity_score))} |
| Dependency Health | ${Number(r.dependency_health_score).toFixed(1)}/10 | ${scoreColor(Number(r.dependency_health_score))} |
| Code Complexity | ${Number(r.code_complexity_score).toFixed(1)}/10 | ${scoreColor(Number(r.code_complexity_score))} |

---

## Repository Metrics

| Metric | Value |
|--------|-------|
| ⭐ Stars | ${Number(r.stars).toLocaleString()} |
| 🍴 Forks | ${Number(r.forks).toLocaleString()} |
| 🐛 Open Issues | ${Number(r.issues).toLocaleString()} |
| 👁 Watchers | ${Number(r.watchers).toLocaleString()} |
| 👥 Contributors | ~${Number(r.contributors).toLocaleString()} |
| 📁 Files | ${Number(r.file_count).toLocaleString()} |
| 📊 Avg File Size | ${Number(r.avg_file_size).toLocaleString()} bytes |
| ⚠️ Large Files (>800 lines) | ${r.large_files_count || 0} |
| 📐 Max Directory Depth | ${r.max_directory_depth || 0} |
| 📦 Dependencies | ${r.dependency_count || 0} |
| 🔒 Dependency Risk | ${r.dependency_risk_level || "Unknown"} |
| 🔄 Commit Frequency | ${r.commit_frequency} |
| 📅 Last Commit | ${r.last_commit_date ? new Date(r.last_commit_date).toLocaleDateString() : "Unknown"} |

---

## Health Indicators

| Indicator | Status |
|-----------|--------|
| Tests | ${checkMark(r.has_tests)} |
| CI/CD | ${checkMark(r.has_ci_cd)} |
| Documentation Folder | ${checkMark(r.has_docs_folder)} |
| Contributing Guide | ${checkMark(r.has_contributing)} |
| License | ${checkMark(r.has_license)} |

---

## Technology Stack

${(r.detected_technologies || []).map((t: string) => `- ${t}`).join("\n") || "No technologies detected"}

---

## Dependency Files

${(r.dependency_files || []).map((f: string) => `- ${f}`).join("\n") || "No dependency files detected"}

---

## AI Analysis Summary

${r.summary || "No summary available."}

${r.explanation?.score_explanation ? `\n### Score Explanation\n${r.explanation.score_explanation}\n` : ""}

---

## Project Explanation

${r.explanation?.purpose ? `**Purpose:** ${r.explanation.purpose}\n` : ""}
${r.explanation?.architecture ? `**Architecture:** ${r.explanation.architecture}\n` : ""}
${r.explanation?.key_modules?.length ? `**Key Modules:** ${r.explanation.key_modules.join(", ")}\n` : ""}
${r.explanation?.how_to_run ? `**How to Run:** ${r.explanation.how_to_run}\n` : ""}

---

## Improvement Recommendations

${(r.recommendations || []).map((rec: string, i: number) => `${i + 1}. ${rec}`).join("\n") || "No recommendations."}

---

*Generated by RepoInsight — AI-Powered GitHub Repository Intelligence Platform*
`;
}

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { repo_id } = await req.json();
    if (!repo_id) {
      return new Response(JSON.stringify({ error: "repo_id required" }), { status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    const { data: repo, error } = await supabase.from("repositories").select("*").eq("id", repo_id).single();
    if (error || !repo) {
      return new Response(JSON.stringify({ error: "Repository not found" }), { status: 404, headers: { ...corsHeaders, "Content-Type": "application/json" } });
    }

    const markdown = generateMarkdownReport(repo);

    return new Response(JSON.stringify({ markdown, filename: `${repo.owner}-${repo.repo_name}-report.md` }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    console.error("Report error:", e);
    return new Response(JSON.stringify({ error: e instanceof Error ? e.message : "Unknown error" }), { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } });
  }
});
