
-- Add new columns for enhanced analysis
ALTER TABLE public.repositories
  ADD COLUMN IF NOT EXISTS community_health_score NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS watchers INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS contributors INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS commit_frequency TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS last_commit_date TEXT,
  ADD COLUMN IF NOT EXISTS has_tests BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_ci_cd BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_docs_folder BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_contributing BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_license BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS readme_length INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS readme_sections JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS detected_technologies JSONB NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS explanation JSONB NOT NULL DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS file_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
